== Overview
Before going into detail with the setup. There are some important topics we need to review.

=== Organization
In the Maritime Cloud an organization is an entity, such as an institution, company or an association, that has a collective goal and is linked to an external environment. Examples, include international organizations such as IMO, IALA, IHO. National authorities such as US Coastguard, Swedish Maritime Administration. Local authorities such as VTS-Oersund, Port Of Rotterdam, Hong Kong SAR. Or commercial companies such as Transas or Maris.

==== Organization ID
All organizations that are registered in the Maritime Cloud must be registered with a unique >=3 letter alphanumeric id.

The id is used in numerous places. For example,  all service specifications from a given organization is prefixed by the organization id. Likewise must all MSDL files from a given organization be organized under the a namespace that starts with the organization id. For example, "package dma.mmsi;" In order to allow easy and consistent sharing and import of MSDL files between organizations.

Examples of valid organizations ids:

** IMO
** IALA
** DMA
** PortOfRotterdam
** VTS-Oeresund

==== Signup
In order to get an organization, its users and any ships the
organization might own on to the Maritime Cloud. The organization needs to  There needs to be
some kind of signup procedure.

For now, we (DMA) will validate all organizations that sign up in some
kind of best effort basis. I do not expect we reach more than a 100
organizations within the next 1-2 years on our current test bed.

How all this vetting is going to be done in the end is up for grabs.
But to avoid getting stalled in the development process. I think we
will just go with simplest solution possible for now.

At a some later point a central Maritime Cloud authority might only
need to verify international organizations and national authorities.
Letting national authorities verify individual companies that try and
sign up. Or something else we decide on.

Most large organizations are divided into departments or suborganizations of some kind. There is currently no support for hirachical organizations.

All organizations have a single root user who has full access to everything in the account (much like a Linux root user). The user is
not meant for day to day operations but only in special cases. For
example, setting up a link to an organizations federated identity
broker where all the organizations users are registered. Or deleting
the organization.

A user of the Maritime Cloud can belong to one and only one organization. For example, if you have to two functions in the maritime sector. One as an employee of a particular company and another as a chairman of a non-profit association. You will have two different users and separate  logins. One that belongs to company and another user that belongs to IALA. Just like you will two different emails @company.com and another at @non-profit-association.org depending on which role you have.

This does not mean that one cannot give a user from one organization access to read a document owned in another organization. Only that a single user can have only a single function within a single organization.
