== Brokered User Federation
In the previous section we discussed digital certificates for use in machine to machine communication. There are no technical reasons to why human users should not be able to use digital certificates to authenticate themselves as well. However, there are some serious practical issues that make it difficult to see them as a general solution for human user authentication. The first issue being that it requires that the certificate must always be present on the computer or mobile phone from which access is made. This is normally not a problem for machine to machine communication. Because, once installed the hardware configuration almost never changes. Unlike human users that use their computer during the day to access information, their mobile phone on the way back from work and their tablet in the evening from home. Making sure that certificates are installed on all these devices and refreshing them once they expire is a lot of effort to require from users. We believe having such a complicated setup would be a major barrier towards successful adoption of MCP. So for now, authentication of human users in MCP will be based on login through a web browser, using brokered federation.

Federation is the means of linking distinct identity management systems to a person's electronic identity and attributes. For example, a shipping company might expose all their users in LDAP or Active Directory to MCP in such a way as they appear as MCP users. Thereby bypassing the need to manage their users directly in MCP. This also means that MCP is not responsible for management of users. In practical terms, federation means that users asked to authenticate in MCP will be redirected to a login webpage supplied by their organization where they can login using their organizational id.

Since the authentication process is the responsibility of the organizations, it is also up to the individual organizations to choose an appropriate authentication method. While most will likely use classic username/password authentication, multi factor security, biometric security or other approaches could be used.

=== OpenID Connect
https://openid.net/connect[OpenID Connect] is the protocol chosen to be used for user federation in MCP, and it should be supported by Service Providers. It is an interoperable authentication protocol based on the https://oauth.net/2/[OAuth 2.0] family of specifications. It uses straightforward REST/JSON message flows with a design goal of "making simple things simple and complicated things possible". It’s uniquely easy for developers to integrate, compared to any preceding Identity protocols.

OpenID Connect lets developers authenticate their users across websites and apps without having to own and manage password files. For the app builder, it provides a secure verifiable, answer to the question: "What is the identity of the person currently using the browser or native app that is connected to me?"

OpenID Connect allows for clients of all types, including browser-based JavaScript and native mobile apps, to launch sign-in flows and receive verifiable assertions about the identity of signed-in users.

// (Identity, Authentication) + OAuth 2.0 = OpenID Connect

OpenID Connect provides authentication details in JWT tokens, that can be encrypted or digitally signed.

=== MCP User Federation Setup
In most federated setups there is 1 step from the website (Service Provider) that need authentication and the Identity Provider, normally presented with a "Log in with X" link, where X could be Facebook, Google, etc. The setup used in MCP has 2 steps, where the first step is MCP Identity Broker which presents the user with a list of available Identity Providers, which is the second step. For a deeper understanding of how this is actually done please read the https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker_overview[Identity Broker overview section from the Keycloak manual]. Keycloak is the software used for MCP Identity Broker.

MCP expects the following attributes in the OpenID Connect JWT Access Token:

[options="header"]
|===
|Attribute|Description
|preferred_username|The username of the user in the parent organization.
|email|The email of the user.
|given_name|Firstname of the user.
|family_name|Lastname of the user.
|name|Full name of the user.
|org|The Maritime Resource Name of the organization the user is a member of.
|permissions|List of permissions for this user assigned by the organization the user is a member of.
|mrn|The Maritime Resource Name of the user.
|===

These attributes will be directly mapped from attributes provided by the organizations Identity Provider, so the Identity Provider must also provide these attributes, except for the "org"-attribute.

=== OpenID Connect Authentication Flow
To illustrate the authentication flows the sequence diagrams below is provided.

The first diagram below shows the standard http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[OpenID Connect Authorization Code Flow] involving a browser being used by the user to access a service in the form of a webpage.

[plantuml, title="Authentication flow"]
....
autonumber
"User (Browser)" -> Service: User clicks "Log in" on service webpage
activate Service
|||
Service -> "User (Browser)": Redirect to MC Identity Broker
autonumber stop
"User (Browser)" -> "MC Identity Broker"
activate "MC Identity Broker"
|||
autonumber resume
"MC Identity Broker" -> "User (Browser)": Present user with list of Identity Providers
"User (Browser)" -> "MC Identity Broker": User chooses an Identity Provider
|||
"MC Identity Broker" -> "User (Browser)": Redirect to Identity Provider
autonumber stop
"User (Browser)" -> "Identity Provider"
activate "Identity Provider"
|||
autonumber resume
"Identity Provider" -> "User (Browser)": Prompt for credentials
"User (Browser)" -> "Identity Provider": Send credentials

"Identity Provider" -> "Identity Provider": Authenticate user

"Identity Provider" -> "User (Browser)": Redirect to MC Identity Broker with code
deactivate "Identity Provider"
autonumber stop
"User (Browser)" -> "MC Identity Broker"

autonumber resume
"MC Identity Broker" -> "Identity Provider": Request token in exchange for code
activate "Identity Provider"
"Identity Provider" -> "MC Identity Broker": Return tokens
deactivate "Identity Provider"

"MC Identity Broker" -> "User (Browser)": Redirect to Service with tokens
deactivate "MC Identity Broker"
autonumber stop
"User (Browser)" -> Service

autonumber resume
Service -> "MC Identity Broker": Request token validation
activate "MC Identity Broker"
"MC Identity Broker" -> Service: Response for token validation
deactivate "MC Identity Broker"
|||
Service -> Service: Extract Organization name and\nattributes for authorization
Service -> "User (Browser)": If token is valid the user is authenticated
deactivate Service
....

The second diagram shows the flow used when an authenticated user is accessing a backend service. For browser based services this scenario is often used when the browser retrieves data from backend services. In this scenario since the user is authenticated, the user has a token that is presented for authentication for the backend service.

[plantuml, title="Backend service authentication flow"]
....
autonumber
"User (Browser)" -> "Backend Service": User accesses Backend Service\nwith data request, includes token
activate "Backend Service"
"Backend Service" -> "MC Identity Broker": Request token validation
activate "MC Identity Broker"
"MC Identity Broker" -> "Backend Service": Response for token validation
deactivate "MC Identity Broker"
"Backend Service" -> "Backend Service": Extract Organization name and\nattributes for authorization
"Backend Service" -> "User (Browser)": Return data response
deactivate "Backend Service"
....

=== Keycloack
Keycloak is one of many products that includes support for OpenID Connect, and it is the product that currently provides MCP Identity Broker which is the cornerstone in MCP user federation.

Keycloak is an open source product developed by RedHat. Keycloak can be set up to work in different ways. It can be set up as an Identity Broker in which case it will link to other Identity Providers, which is what MCP Identity Broker does, or it can be set up to work as an Identity Provider, using either a database or LDAP/AD as a backend. Due the ability to connect to LDAP/AD, Keycloak can be used as quick and easy way to set up a Identity Provider.

=== Getting connected to MCP
If your organizations wishes to connect to MCP as an Identity Provider, to enable your uses to authenticate in MCP, please contact Oliver Haagh at mailto:oliver@dmc.international[oliver@dmc.international] in order to set it up. Note that currently you need to expose interfaces that supports either OpenID Connect or SAML2.

Within the scope of the EfficienSea2 and STM validation projects, organizations can get users registered in special project Identity Providers, supplied by MCP. To join MCP please fill out the form at https://management.maritimecloud.net/#/apply[Apply].

[[setup-oidc-idp]]
==== Setting up an OpenID Connect Identity Provider
OpenID Connect is supported by the latest ADFS and http://keycloak.org[Keycloak] releases. MCP Identity Broker only supports the http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[OpenID Connect Authorization Code Flow] when connecting to Identity Providers. This limitation only applies when the Identity Broker connects to Identity Providers, not when Services/Clients connects to the Identity Broker.

As default MCP Identity Broker expect the following attributes to be provided by an OpenID Connect Identity Provider:

[options="header"]
|===
|Attribute|Description
|preferred_username|The username of the user in the parent organization.
|email|The email of the user.
|given_name|Firstname of the user.
|family_name|Lastname of the user.
|name|Full name of the user.
|permissions|List of permissions for this user assigned by the organization the user is a member of.
|===

If your Identity Provider has the values in different attributes, some mapping can be set up.

The Identity Broker will generate and attach the organizations MRN and the users MRN to the user.

==== Setting up an OpenID Connect Identity Provider for multiple organizations
MCP has some special Identity Providers that handles the authentication for multiple organizations. Current examples are "IALA" and "BIMCO ExtraNet". These Identity Providers are responsible for vetting the organizations they provide authentication for, so that it is confirmed that the organization is who they claim to be. New organizations can be added by these Identity Providers. Since MCP currently needs to know about organizations centrally to be able to (among other things) issue certificates, some extra information is needed from these Identity Providers, to be able to create them in the central Identity Registry, if they are not already known.

The extra information must be given as attributes, in addition to the attributes mentioned in <<setup-oidc-idp>>:

As default MCP Identity Broker expect the following attributes to be provided by an OpenID Connect Identity Provider:

[options="header"]
|===
|Attribute|Description
|mrn|The Maritime Resource Name of the user.
|org|The Maritime Resource Name of the parent organization of the user.
|org-name|Human readable name of the parent organizations.
|org-address|Address of the organization. It must be without linebreaks, ending with comma and the country of the address.
|===

Note that the MRN must be on the form "urn:mrn:mcl:user:dma@iala:thc" and "urn:mrn:mcl:org:dma@iala" for user and organization respectively. In this case the organization is "dma" whos identity is guaranteed by "iala".


==== Setting up an SAML2 Identity Provider
SAML2 is supported by older ADFS releases.

[options="header"]
|===
|Attribute|Description
|NAMEID|The username of the user in the parent organization.
|http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress|The email of the user.
|http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname|Firstname of the user.
|http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname|Lastname of the user.
|http://schemas.microsoft.com/ws/2008/06/identity/claims/role|List of permissions for this user assigned by the organization the user is a member of.
|===

If your Identity Provider has the values in different attributes, some mapping can be set up.

The Identity Broker will generate and attach the organizations MRN and the users MRN to the user.
